sudo: false
language: node_js
node_js:
    - "0.12"

before_script:
    - npm install bower -g
    - bower install

script: npm run travis

after_success: NODE_ENV=test cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage